name: CI/CD Pipeline

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    env:
      OPEN_WEATHER_MAP_PUBLIC_API: TestEnv
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Read variable
        run: echo var name = ${{ vars.APP_NAME }}

      - name: Read environment
        run: echo env name = ${{ env.OPEN_WEATHER_MAP_PUBLIC_API }}

      # - name: Install dependencies
      #   run: npm install

      # - name: Build and run tests
      #   run: |
      #     NODE_ENV=test npm test &&
      #     npm run build
