name: CI/CD Pipeline

on:
  pull_request:
  push:
    branches:
      - master
      - develop
env:
  # Setting an environment variable with the value of a configuration variable
  OPEN_WEATHER_MAP_PUBLIC_API: ${{ vars.NEXT_PUBLIC_OPEN_WEATHER_PUBLIC_BASE_URL }}

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    env:
      Test: TestEnv
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Test print env
        run: |
          echo env name = ${{ env.NEXT_PUBLIC_OPEN_WEATHER_PUBLIC_BASE_URL }}
          echo env test = $Test

      # - name: Install dependencies
      #   run: npm install

      # - name: Build and run tests
      #   run: |
      #     NODE_ENV=test npm test &&
      #     npm run build
